### PR TITLE
Recreating site for 2022

### PR DESCRIPTION
**Pull request by codeperfectplus**
## Changelog

1. Contributors.json updated
2. New Blog Updated
3. Package updated for Ruby 3.0
4. Loading Data from JSON instead of Hard code.
5. Loading Project data from JSON instead of Hard code
6. 2020 Developers Data moved to contributors_old.json

### CODE REVIEW

**Comment by codeperfectplus** [comment]
@DrakeEntity  I will be adding New Developer's Data on-site soon. 
The Main Page card will update in the next PR.
Special Thanks to @reveurguy He developed the site in 2020.

**Comment by reveurguy** [comment]
Hey @codePerfectPlus, I'd be happy to make changes to the site if a re-creation is required!

**Comment by codeperfectplus** [comment]
@reveurguy making some changes. let me know If you have some ideas to work on. I also have some ideas in my mind.

**Review by DrakeEntity — CHANGES_REQUESTED** [review]
add .jekyll-cache in gitignore

**Comment by DrakeEntity** [comment]
Don't Upload more pictures to repos. Create a link.

**Comment by codeperfectplus** [comment]
Deleted the image from REPO and added the link from another source.

**Review by DrakeEntity — APPROVED** [review]

**Pull request merged**
